const REGEX_EMAIL = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z]+)*$/;
const REGEX_LOGIN = /^\w{3,16}$/;
const REGEX_PASSWORD = /^(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*])[\w!@#$%^&*]{8,}$/;
const REGEX_NAME_SURNAME = /^\w+$/;
const FORM_ID = "#reg";
const FORM_NAME = "reg";
const LOGIN_ID = "#login";
const EMAIL_ID = "#email";
const NAME_ID = "#name";
const SURNAME_ID = "#surname";
const PASSWORD_STRING = "password";
const INPUT_STRING = 'input';
const CLASS_STRING = 'class';
const INVALID_STRING = "invalid";
const VALID_STRING = "valid";
const FORM_INVALID_STRING = "formInvalid";
const PRIVACY_POLICY_ID = "#privacy-policy";
const CHECKED_STRING = "checked";
const INCORRECT_INPUT_STRING = "Incorrect input";
const INCORRECT_LOGIN = "Incorrect login";
const INCORRECT_EMAIL = "Incorrect email";
const INCORRECT_PASSWORD_STRING = "Incorrect password";
const INCORRECT_CONFIRM_PASSWORD_STRING = "Incorrect confirm password"
const CONFIRM_PASSWORD_STRING = "confirmPassword";
const AGREE_WITH_PRIVACY_POLICY_STRING = "Agree with privacy policy";